/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnyInput {
        "disabled": boolean;
        "letters": string;
        "targetFirstLetter": string;
    }
    interface GeoInput {
        "disabled": boolean;
    }
}
declare global {
    interface HTMLAnyInputElement extends Components.AnyInput, HTMLStencilElement {
    }
    var HTMLAnyInputElement: {
        prototype: HTMLAnyInputElement;
        new (): HTMLAnyInputElement;
    };
    interface HTMLGeoInputElement extends Components.GeoInput, HTMLStencilElement {
    }
    var HTMLGeoInputElement: {
        prototype: HTMLGeoInputElement;
        new (): HTMLGeoInputElement;
    };
    interface HTMLElementTagNameMap {
        "any-input": HTMLAnyInputElement;
        "geo-input": HTMLGeoInputElement;
    }
}
declare namespace LocalJSX {
    interface AnyInput {
        "disabled"?: boolean;
        "letters": string;
        "targetFirstLetter": string;
    }
    interface GeoInput {
        "disabled"?: boolean;
    }
    interface IntrinsicElements {
        "any-input": AnyInput;
        "geo-input": GeoInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "any-input": LocalJSX.AnyInput & JSXBase.HTMLAttributes<HTMLAnyInputElement>;
            "geo-input": LocalJSX.GeoInput & JSXBase.HTMLAttributes<HTMLGeoInputElement>;
        }
    }
}
